### ISSUE TITLE
Add Icons to Filters

### ISSUE THREAD

**Issue by MasterOfTheTiger** [plujon/filters#6]
We should add icons to all the filters listed. 

@plujon You should add the hacktoberfest label to have other people help out with this.

In addition, a license is very much needed.

**Comment by plujon** [comment]
Including an icon will not only cause the icon to show up.  It will also cause the corresponding product to be "hoisted" in the table because all products with icons are displayed early in the table, before any non-iconified products.  This was a hack I added long ago to help point people to more well known / usable products.  Hence, I only added icons for products I considered worthy.

Adding icons can be done, but care should be taken to preserve some sort of ordering for the average Joe.

**Comment by MasterOfTheTiger** [comment]
Ah. That makes sense now. I saw that it boosts it. I will see if I can add some other system to replace it. Maybe some hidden points systems that contain levels of recommendation.

**Comment by MasterOfTheTiger** [comment]
Closing this for now until such a hack is made.
